feat : Refactored Code That used socket methods
Dun-sin/Whisper pull request #323
Opened 2023-09-28 15:49 UTC by govardhanshah456

# Fixes Issue

**My PR closes #310 **

# 👨‍💻 Changes proposed(What did you do ?)
- Made Separate Definitions for Event Listeners and Event Emitters.
- Replaced them in all the files with the newly made definitions.
# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

- I had tried to make a common constants.js file but for that I had to define a separate ES-Lint Configuration only for that single file, so I moved it to client and server older Respectively.
# 📷 Screenshots

2023-09-28 16:47 UTC, Dun-sin commented on server/constants.js
> +module.exports = { CHAT_EVENTS }
won't `module.exports = CHAT_EVENTS` give a much cleaner code. That way, you just use `const {NEW_EVENT_ADDING}`

2023-09-28 18:19 UTC, Dun-sin requested changes

2023-09-28 18:19 UTC, Dun-sin commented on server/constants.js
they shouldn't be in separate files, you were going the right way at first, use one file in the root folder for constants

2023-09-28 18:22 UTC, govardhanshah456 commented on server/constants.js
My very first approach was that only, but it was throwing error : no eslint configuration was found for constants.js

2023-09-28 18:24 UTC, Dun-sin commented on server/constants.js
i see, here's a fix https://stackoverflow.com/questions/38173326/no-eslint-configuration-found-error

2023-09-28 19:47 UTC, govardhanshah456 commented on server/constants.js
Still it's the same, the project structure is like this: 
Whisper
|_Client
|_Server
|_Constant.js

and lint requires package.json so we can execute it in either client or server so constant.js is left out without linting, we cannot place it inside client or server as well as both are deployed independent so any fix you can think of this?

2023-09-28 19:49 UTC, Dun-sin commented on server/constants.js
Did every solution in the link fail?

2023-09-28 19:54 UTC, govardhanshah456 commented on server/constants.js
for them to work, I need a package.json at the top level too where constant.js is there but package.json is only inside client and server.

2023-09-28 19:57 UTC, Dun-sin commented on server/constants.js
I'm not disagreeing with you, I'm asking a question

2023-09-28 20:04 UTC, govardhanshah456 commented on server/constants.js
Yeah, all are basically saying same thing, you cannot run ESLint without package.json and other solutions i tried are failing

2023-09-28 20:22 UTC, Dun-sin commented on server/constants.js
Okay, can you try using eslint ignore in the client folder where the config is to ignore constant.js.?

2023-09-28 20:40 UTC, govardhanshah456 commented on server/constants.js
yes

2023-09-28 21:05 UTC, govardhanshah456 commented on server/constants.js
Also, in constant.js we can either follow ES6 or commonJs method for exporting data, so in any of the two ways we choose we would have trouble setting up the other side case, i.e. selecting ES6 would cause trouble on nodejs side and vice versa. what to choose?

2023-09-28 21:34 UTC, Dun-sin commented on server/constants.js
Good point, didn't think of that🤔 let me hear your opinion, what do you think we should do

2023-09-29 05:05 UTC, govardhanshah456 commented on server/constants.js
Looks like we have an easy fix. We can declare constants.js as constants.json and that's it, it will work

2023-09-29 05:08 UTC, Dun-sin commented on server/constants.js
I think that will also fix the eslint issue, right?

2023-09-29 05:17 UTC, govardhanshah456 commented on server/constants.js
yes

2023-09-29 06:20 UTC, Dun-sin approved these changes
Looks good,do you want me to merge it when hacotberfest starts?

2023-09-29 07:15 UTC, govardhanshah456 commented
> Looks good,do you want me to merge it when hacotberfest starts?

Yes, thanks

2023-09-30 20:00 UTC, merged