feat : added send message feature by ctrl+enter key #288
Dun-sin/Whisper pull request #332
Opened 2023-09-29 09:14 UTC by aman44444

# Fixes Issue

**My PR closes #288**
Added a feature that can send message by ctrl + enter key 

# 👨‍💻 Changes proposed(What did you do ?)

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

2023-09-29 09:19 UTC, Dun-sin requested changes

2023-09-29 09:19 UTC, Dun-sin commented on client/src/App.jsx
please revert this change, it has nothing to do with your PR

2023-09-29 09:19 UTC, Dun-sin commented on client/src/components/Chat.jsx
> +        }
use the handle Submit function instead

2023-09-30 05:59 UTC, aman44444 commented
@Dun-sin my server is not working but i can add handlesubmit if you want?

2023-09-30 06:00 UTC, Dun-sin commented
> @Dun-sin my server is not working but i can add handlesubmit if you want?

follow the changes, answer the question and fix the errors, I don't know what you mean by your server isn't working.

But that's what you need to do.

2023-10-01 16:02 UTC, closed without merging