fix: refactor chat.jsx file
Dun-sin/Whisper pull request #400
Opened 2023-10-11 11:09 UTC by MaybeSHAH

# Fixes Issue

**My PR closes #272**

# 👨‍💻 Changes proposed(What did you do ?)
Keeping everything organised 
Created a class to maintain all functions of chat.jsx
import the class in chat.jsx 
and using instance of class to call functions.

# ✔️ Check List (Check all the applicable boxes)

- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

2023-10-11 13:19 UTC, Dun-sin commented
You said it yourself, this is a refactor not a fix, so please change the PR title accordingly

2023-10-15 09:41 UTC, Dun-sin requested changes

2023-10-15 09:41 UTC, Dun-sin commented on client/src/components/ChatHelper.js
please stick to the project code format and don't use classes

2023-10-15 09:41 UTC, Dun-sin commented on client/src/components/ChatHelper.js
> +}
also make sure to keep an empty line at the end of each file

2023-10-16 04:59 UTC, MaybeSHAH commented on client/src/components/ChatHelper.js
@Dun-sin  Okay

2023-10-16 05:28 UTC, MaybeSHAH commented on client/src/components/ChatHelper.js
without classes every functions need necessary data and dependencies as parameter and it is not good to send it eveytime while calling individual function !

2023-10-16 08:15 UTC, Dun-sin commented on client/src/components/ChatHelper.js
also fix the merge conflict

2023-10-17 05:45 UTC, MaybeSHAH commented on client/src/components/ChatHelper.js
@Dun-sin Yes, I am doing it.

2023-10-17 10:22 UTC, closed without merging