Updating Settings.jsx frontend text color
Dun-sin/Whisper pull request #418
Opened 2023-10-15 11:34 UTC by AaadityaG

# Fixes Issue

**My PR closes #401**

# 👨‍💻 Changes proposed(What did you do ?)
Adding inline CSS to the three Form.HelpText component.

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

###  Before : 
![Whisper _ Chat Application - Google Chrome 15-10-2023 04_51_49 PM](https://github.com/Dun-sin/Whisper/assets/114663382/0ad80c7d-a872-4f6a-8dde-11fabca41910)

###  After : 
![Whisper _ Chat Application — Mozilla Firefox 15-10-2023 04_14_45 PM](https://github.com/Dun-sin/Whisper/assets/114663382/4f753108-e760-4081-af29-e3fe1a95aeb1)

2023-10-15 12:32 UTC, Dun-sin requested changes

2023-10-15 12:32 UTC, Dun-sin commented on client/src/pages/Settings.jsx
use tailwind

2023-10-15 13:44 UTC, AaadityaG commented on client/src/pages/Settings.jsx
Done Sir!

2023-10-15 14:38 UTC, Dun-sin requested changes

2023-10-15 14:38 UTC, Dun-sin commented on client/src/pages/Settings.jsx
> +                            <Form.HelpText className='text-zinc-600 text-xs decoration-white'>
Wrong tailwind class

2023-10-16 06:07 UTC, AaadityaG commented on client/src/pages/Settings.jsx
> +                            <Form.HelpText className='text-zinc-600 text-xs decoration-white'>
My bad...😑

2023-10-16 08:23 UTC, Dun-sin approved these changes
You did great, thanks for contributing, I hope you will stick around and continue to contribute to this project.

Consider giving this project a star and joining the community discord server if you haven't for more resources and opportunities to connect with others. [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

2023-10-16 08:23 UTC, merged