feat(chat): added emoji picker
Dun-sin/Whisper pull request #449
Opened 2023-10-16 18:38 UTC by amitabh-sahu

# Fixes Issue
**My PR closes #423**

# 👨‍💻 Changes proposed(What did you do ?)
I have added an emoji picker for chat using the emoji-picker-react library.

# ✔️ Check List (Check all the applicable boxes)
- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR are clear and explain the approach.

##  Note to reviewers
This PR has a dependency added on the client side.

# 📷 Screenshots
https://github.com/Dun-sin/Whisper/assets/90052329/8a3395e4-ef45-4c00-ae13-cd5b8925c401

2023-10-16 19:43 UTC, Dun-sin commented
best PR so far🥇
just a change, when the user has picked an emoji, the message box isn't focused back, which is a very annoying inconvenience

2023-10-16 19:43 UTC, Dun-sin requested changes

2023-10-16 19:43 UTC, Dun-sin commented on client/src/components/EmojiPicker.jsx
> +};
add an ending empty line at the end of this file

2023-10-17 10:06 UTC, amitabh-sahu commented
Made requested changes

2023-10-17 10:25 UTC, Dun-sin approved these changes
You did great, thanks for contributing, I hope you will stick around and continue to contribute to this project.

Consider giving this project a star and joining the community discord server if you haven't for more resources and opportunities to connect with others. [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

2023-10-17 10:25 UTC, merged