feat: Fixes issue #476
Dun-sin/Whisper pull request #482
Opened 2023-10-19 17:06 UTC by kapooraryan

# Fixes Issue

Closes #476 

# 👨‍💻 Changes proposed(What did you do ?)

Called the function createBrowserNotification to send a browser notification when one of the user leaves the chat but isn't on the page.

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

I have not incluced the requestBrowserNotificationPermissions function here but do let me know if I should, or if not the code should just work fine.

# 📷 Screenshots

NA

2023-10-19 18:10 UTC, Dun-sin commented
@kapooraryan use a better title, don't be lazy

2023-10-19 18:25 UTC, kapooraryan commented
> @kapooraryan use a better title, don't be lazy

Hey, @Dun-sin it's updated now.

2023-10-19 18:26 UTC, Dun-sin commented
> > @kapooraryan use a better title, don't be lazy
> 
> Hey, @Dun-sin it's updated now.
> 
> 

A summary pls😭

2023-10-19 18:31 UTC, Dun-sin commented
@kapooraryan look at other PRs and learn how to make a better PR title

2023-10-19 18:53 UTC, kapooraryan commented
> @kapooraryan look at other PRs and learn how to make a better PR title

Is it better now @Dun-sin 😅?

2023-10-19 18:54 UTC, Dun-sin commented
> > @kapooraryan look at other PRs and learn how to make a better PR title
> 
> Is it better now @Dun-sin 😅?

Summary, if you can't put it in less than 6-8 words it's not a summary

2023-10-19 18:57 UTC, kapooraryan commented
> No, a Summary, if you can't put it in less than 6-8 words it's not a summary or a good PR title, also when you checked other PRs did you see `fixes <whatever>`

No, I did not. Hope I have got it right.

2023-10-20 05:45 UTC, Dun-sin requested changes

2023-10-20 05:45 UTC, Dun-sin commented on client/src/components/BuddyMatcher.jsx
remove all format changes here

2023-10-20 10:28 UTC, kapooraryan commented on client/src/components/BuddyMatcher.jsx
Done as per requested format @Dun-sin .

2023-10-20 15:35 UTC, Dun-sin commented on client/src/components/BuddyMatcher.jsx
> +			createBrowserNotification('Chat Closed', 'This chat is closed! Would you like to search for a new buddy?');
```suggestion
			createBrowserNotification('Chat Closed', 'Your buddy left the chat');
```

2023-10-20 15:36 UTC, merged