feat:changed the style of dropdown properly
Dun-sin/Whisper pull request #556
Opened 2023-10-27 13:00 UTC by Roshanchau

# Fixes #523

**My PR closes #issue_number_here**

# 👨‍💻 Changes proposed(What did you do ?)
- changed the style of the dropdown

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

2023-10-27 14:10 UTC, Dun-sin commented
> # PR Compliance Checks
> 
> Thank you for your Pull Request! We have run several checks on this pull request in order to make sure it's suitable for merging into this project. The results are listed in the following section.
> ## Conventional Commit PR Title
> 
> In order to be considered for merging, the pull request title must match the specification in [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). You can edit the title in order for this check to pass. Most often, our PR titles are something like one of these:
> 
>     * docs: correct typo in README
> 
>     * feat: implement dark mode"
> 
>     * fix: correct remove button behavior
> 
> 
> Linting Errors
> 
>     * Found type "null", must be one of "feat","fix","docs","style","refactor","perf","test","build","ci","chore","revert"
> 
>     * No subject found
> 
> 
> ## Watched Files
> 
> This pull request modifies specific files that require careful review by the maintainers.
> 
> Files Matched
> 
>     * package-lock.json

@Roshanchau 
Please fix this error, if you don't know how, try this:
- Read the error carefully or read the contributing file
- Checkout past merged Pull requests to see how they were done for it to be merged

> Note: you can edit your PR message, this PR won't be merged if the error isn't gone and you have a week max to fix it before the PR gets closed without being merged

2023-10-28 14:12 UTC, Roshanchau commented
I changed the commit message hope it is convenient to merge.

2023-10-28 14:49 UTC, Dun-sin commented
> # PR Compliance Checks
> Thank you for your Pull Request! We have run several checks on this pull request in order to make sure it's suitable for merging into this project.  The results are listed in the  following section.
> 
> ## Conventional Commit PR Title
> In order to be considered for merging, the pull request title must match the specification in  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). You can edit the title in order for this check to pass.
> Most often, our PR titles are something like one of these:
> - docs: correct typo in README
> - feat: implement dark mode"
> - fix: correct remove button behavior
> 
> Linting Errors
> 
> - Found type "null", must be one of "feat","fix","docs","style","refactor","perf","test","build","ci","chore","revert"
> - No subject found
> 
> ## Watched Files
> This pull request modifies specific files that require careful review by the maintainers.
> 
> Files Matched
> 
> - package-lock.json

@Roshanchau you are good to go when this error changes

2023-10-29 07:20 UTC, Roshanchau commented
> > # PR Compliance Checks
> > Thank you for your Pull Request! We have run several checks on this pull request in order to make sure it's suitable for merging into this project.  The results are listed in the  following section.
> > ## Conventional Commit PR Title
> > In order to be considered for merging, the pull request title must match the specification in  [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). You can edit the title in order for this check to pass.
> > Most often, our PR titles are something like one of these:
> > 
> > * docs: correct typo in README
> > * feat: implement dark mode"
> > * fix: correct remove button behavior
> > 
> > Linting Errors
> > 
> > * Found type "null", must be one of "feat","fix","docs","style","refactor","perf","test","build","ci","chore","revert"
> > * No subject found
> > 
> > ## Watched Files
> > This pull request modifies specific files that require careful review by the maintainers.
> > Files Matched
> > 
> > * package-lock.json
> 
> @Roshanchau you are good to go when this error changes

2023-10-29 07:22 UTC, Roshanchau commented
Is it done now ?

2023-10-29 09:57 UTC, Dun-sin requested changes
Remove all format changes and just leave the required change

2023-10-29 13:17 UTC, Roshanchau commented
do you mean the format changes in the code or something else i didn't get it.

2023-10-29 15:19 UTC, Dun-sin commented
> do you mean the format changes in the code or something else i didn't get it.

yes in the code

2023-10-30 14:02 UTC, Roshanchau commented
I removed the format changes.

2023-10-31 11:06 UTC, Dun-sin commented on client/src/components/Anonymous.jsx
> +    <div className="flex justify-between gap-2 flex-wrap">
```suggestion
    <div className="flex items-center justify-between gap-2 flex-wrap">
```

2023-10-31 11:06 UTC, Dun-sin approved these changes
You did great, thanks for contributing, I hope you will stick around and continue to contribute to this project.

Consider giving this project a star and joining the community discord server if you haven't for more resources and opportunities to connect with others. [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

2023-10-31 11:07 UTC, merged