fix: Room not found
Dun-sin/Whisper pull request #584
Opened 2024-01-03 23:00 UTC by MJinH

# Fixes Issue

**My PR closes #577 **

# 👨‍💻 Changes proposed(What did you do ?)

1. commented out the lines in anonymous.tsx file. Had an issue where the socket would connect on the server side but immediately disconnect on the client side, which was causing the `NEW_EVENT_CHAT_RESTORE` event to not work properly.

2. After debugging, noticed that the `createChat` function wasn't being called properly in the anonymous.tsx file. suspect this was because it was being called before the provider was initialized, so wrapped the components with `ChatProvider` in the _app.tsx file and confirmed that it was working correctly.

# ✔️ Check List (Check all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.

## Note to reviewers

# 📷 Screenshots

2024-01-04 03:59 UTC, Dun-sin commented
Will review this later in the day @MJinH in the mean time, please remove the package files, don't delete them but remove them from your PR. Thanks

2024-01-04 08:00 UTC, Dun-sin commented
Can't do that, deleting it from here is deleting it from the actual code, we don't want that.

You have to close this PR, and raise it again without the package files in it

2024-01-04 08:02 UTC, Dun-sin reviewed
Leave the naming

2024-01-04 08:04 UTC, Dun-sin requested changes
Please remove everything that doesn't have to do with the issue, like changing name or formatting?

Also why are you calling context twice as we've already called it in PageWrapper.tsx, so either you remove it from there and leave your changes or vice versa, but can't be both

2024-01-04 09:36 UTC, MJinH commented
Could you please check this? in the ChatContext.tsx file, when the name is "chatId" in the createChat, it seems to result in 'undefined' in the chatReducer, causing a room not found error as shown in the image. When using 'id', it looks like it's assigned correctly. Please let me know if i missed something. Also, yes you're right. I forgot to remove the context in the PageWrapper.tsx file.  

![Screenshot (211)](https://github.com/Dun-sin/Whisper/assets/97130553/faaf7ebd-a19d-4dd3-9fba-837dba08fb9a)


![Screenshot (208)](https://github.com/Dun-sin/Whisper/assets/97130553/7e690113-62c3-454d-af33-a5e39fae2b0e)

2024-01-04 10:36 UTC, Dun-sin commented
> Could you please check this? in the ChatContext.tsx file, when the name is "chatId" in the createChat, it seems to result in 'undefined' in the chatReducer as shown in the image. When using 'id', it looks like it's assigned correctly. Please let me know if i missed something. Also, yes you're right. I forgot to remove the context in the PageWrapper.tsx file.
> 
> ![Screenshot (211)](https://private-user-images.githubusercontent.com/97130553/294139375-faaf7ebd-a19d-4dd3-9fba-837dba08fb9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjQ3MDgsIm5iZiI6MTcwNDM2NDQwOCwicGF0aCI6Ii85NzEzMDU1My8yOTQxMzkzNzUtZmFhZjdlYmQtYTE5ZC00ZGQzLTlmYmEtODM3ZGJhMDhmYjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDEwMzMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ZmQ2MDcyZDViYmU0MDY4YmM0OTkxOWVjOTE3OGNhMThkODEyOGFkYzE1ODMxMzg4MGM4NDlmYjYwNmJjZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mZ0CVLZPQIxCoHUd5fkP1qrN2oWVGhgK5uXv1LrMH6Y)
> 
> ![Screenshot (208)](https://private-user-images.githubusercontent.com/97130553/294139837-7e690113-62c3-454d-af33-a5e39fae2b0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjQ3MDgsIm5iZiI6MTcwNDM2NDQwOCwicGF0aCI6Ii85NzEzMDU1My8yOTQxMzk4MzctN2U2OTAxMTMtNjJjMy00NTRkLWFmMzMtYTVlMzlmYWUyYjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDEwMzMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyN2MxNGY4YmFmNDExMjZiMjdkNGViNjI5ZDAyNzdmY2Y3ZDkxY2ZjZTJhNTJiZmUxNDU4MjVlNGJjMzQxZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6oKaBAUOLLvDUOtE2eTB9KVbL1sDALLgrX6g2rasft8)

i guess the issue comes from here:
remove the id and leave the chatId, should fix it, can't believe i missed that
https://github.com/Dun-sin/Whisper/blob/94b3b503ac05dd3d4cf6e9ad6250da494cead95c/src/reducer/chatReducer.ts#L24

2024-01-04 11:33 UTC, MJinH commented
got it, and if the provider is in PageWrapper, the createChat in anonymous.tsx doesn't seem to be called properly. When debugging, it gets called as `createChat: () => {}` and exits immediately. can you please check this as well?

I'll fix those and recommit later. Thank you.

2024-01-04 12:13 UTC, Dun-sin requested changes

2024-01-04 12:13 UTC, Dun-sin commented on src/reducer/chatReducer.ts
> +        clonedState[room].messages[messageId].oldMessages = oldMessages;
remove this change

2024-01-04 12:13 UTC, Dun-sin commented on src/pages/api/server/index.ts
remove this change as well

2024-01-04 12:13 UTC, Dun-sin commented on src/pages/anonymous.tsx
here too

2024-01-04 12:13 UTC, Dun-sin commented on src/types/contextTypes.ts
here too

2024-01-04 12:24 UTC, Dun-sin commented
Also @MJinH what exactly do you mean in Anonmyous.tsx?

2024-01-04 21:31 UTC, MJinH commented
What I mean is, when ChatProvider is in PageWrapper, createChat is exeucted like this
[room-1.webm](https://github.com/Dun-sin/Whisper/assets/97130553/7e262612-3d39-4d67-b051-b362565c385d)



and this is when the provider is in _app.tsx
![room-2](https://github.com/Dun-sin/Whisper/assets/97130553/345865e6-2c5a-4c85-8407-bea6393ad3be)

2024-01-05 06:48 UTC, Dun-sin commented
> What I mean is, when ChatProvider is in PageWrapper, createChat is exeucted like this
> [room-1.webm](https://github.com/Dun-sin/Whisper/assets/97130553/7e262612-3d39-4d67-b051-b362565c385d)
> 
> 
> 
> and this is when the provider is in _app.tsx
> ![room-2](https://github.com/Dun-sin/Whisper/assets/97130553/345865e6-2c5a-4c85-8407-bea6393ad3be)
> 

I see your point, yours is a better way then💪🏽 but the other things still count

2024-01-06 03:25 UTC, Dun-sin requested changes

2024-01-06 03:25 UTC, Dun-sin commented on src/reducer/chatReducer.ts
> +}
Here too, I think there was also an empty line at the end instead

2024-01-06 07:43 UTC, Dun-sin approved these changes
You did great, thanks for contributing, I hope you will stick around and continue to contribute to this project.

Consider giving this project a star and joining the community discord server if you haven't for more resources and opportunities to connect with others. [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

2024-01-06 07:51 UTC, merged