feat: move reconnect banner to a new component
Dun-sin/Whisper pull request #692
Opened 2024-09-06 12:14 UTC by LuseBiswas

# Fixes Issue

**My PR closes #691 **

# 👨‍💻 Changes proposed(What did you do ?)
I just made another component i.e. ReconnectBanner.jsx in Components 📁 of Client and And applied it in BuddyMatcher.jsx by pasing props.

# ✔️ Check List (Check all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

2024-09-06 12:18 UTC, LuseBiswas commented
@Dun-sin I checked all the things and I found out that there is restirictions in a Max-Character Limit in One Line. So I break the Line into several parts to encounter that error.
And there are some components which are not in use but declared so I removed that too.
Hope this will make the build perfect. Rest I still not able to get you vercel link you are saying to me. 

I know its sound silly but can you please provide to me. Actually I am new in Open Source Contribution. SO thats why.

2024-09-06 14:35 UTC, Dun-sin commented
@LuseBiswas pls stop creating new prs and just edit and fix your current PR, google it if you don't know how

secondly, you didn't fill the PR properly and the compliance error is still there(look at what i said in the last PR you just closed)

2024-09-06 14:40 UTC, Dun-sin requested changes

2024-09-06 14:40 UTC, Dun-sin commented on client/src/components/BuddyMatcher.jsx
> +		//Changes made here with moviing reconnector to another component.
no need for the comment

2024-09-06 14:40 UTC, Dun-sin commented on client/src/components/BuddyMatcher.jsx
> +//import { useNavigate, Link } from 'react-router-dom';
no need to comment it, git shows you the history already

2024-09-06 14:40 UTC, Dun-sin commented on client/src/components/BuddyMatcher.jsx
> +//import { PiPlugsLight } from 'react-icons/pi';
same here no need to comment it out, just remove it if you aren't using it

2024-09-06 14:40 UTC, Dun-sin commented on client/src/components/ReconnectBanner.jsx
> +// Define the expected prop types
no need for a comment here either

2024-09-06 14:40 UTC, Dun-sin commented on client/src/components/ReconnectBanner.jsx
> +import PropTypes from 'prop-types'; // Import the PropTypes package
no need for the comment here

2024-09-06 14:40 UTC, Dun-sin commented on package-lock.json
remove this file and don't delete it.

```
Find the original version of the file, either on your fork if you forked from the main repository, or on the repository from which you cloned your local repository.
Copy the entire content of the file and paste it into your copy of the file.
Commit the new changes if necessary:
If you had not yet committed your unwanted changes, then you don’t need to do any more.
If you’d already committed your unwanted changes, create another commit now. The new commit wipes out your previous changes.
If you’d already pushed the changes up to a remote repository, push the new commit now too.
```

2024-09-06 14:40 UTC, Dun-sin commented on client/src/components/ReconnectBanner.jsx
pls run prettier locally, look at the package.json on the command to do that

2024-09-06 15:05 UTC, LuseBiswas commented
@Dun-sin Thankyou for guiding me in detail. I had done all the changes as you said. Let me know if any other changes I need to do.

2024-09-07 05:17 UTC, Dun-sin requested changes
my mistake, pls remove all(don't delete) the files that you didn't work on

2024-09-07 05:18 UTC, Dun-sin commented
@LuseBiswas also fill the PR template properly, you can edit it, check the 3 dots by the side of it

2024-09-07 07:04 UTC, LuseBiswas commented
Hey @Dun-sin I just made all the changes:-
First:- I edited my PR Template by explaining my approcah and changes I made.
Second:- I remove (I dont delete it this time) all the files which I did not work on.

But there is an extra empty commit there named "[Merge resolved: Your commit message here]" it is done by me intentionally, actually I was facing problem to reset the last commit so I had to force the commit. Kindly look at that while merging it.

2024-09-07 07:06 UTC, LuseBiswas commented
@Dun-sin if any changes I need to make then let me know. I'll make that. Because of your support I learnt so much new things.🙂

2024-09-07 07:11 UTC, Dun-sin requested changes

2024-09-07 07:11 UTC, Dun-sin commented on package-lock.json
still need to remove this

2024-09-07 07:11 UTC, Dun-sin commented on client/src/components/BuddyMatcher.jsx
> +		//Changes made here with moviing reconnector to another component.
remove this comment

2024-09-07 07:11 UTC, Dun-sin commented on client/src/components/ReconnectBanner.jsx
don't think you ran prettier for this file, do you have prettier installed on your VSCode(it should automatically do this on each save)

2024-09-07 07:15 UTC, Dun-sin commented
> Hey @Dun-sin I just made all the changes:- First:- I edited my PR Template by explaining my approcah and changes I made. Second:- I remove (I dont delete it this time) all the files which I did not work on.
> 
> But there is an extra empty commit there named "[Merge resolved: Your commit message here]" it is done by me intentionally, actually I was facing problem to reset the last commit so I had to force the commit. Kindly look at that while merging it.

don't worry about the commit, that's normal, i will handle that when i merge this. you still need to provide the screenrecording in your PR. It can be a screenshot like in this PR -> #683 or a screenrecoding like this PR -> #680

2024-09-08 21:49 UTC, LuseBiswas commented
Hey @Dun-sin its been a day I am trying to get that reconnect banner option on the web app. I tried to being offline and decreasing my internet speed through Network tab from inspection. But I am unable to get that.

It is not like this problem I am facing on my local website. Its even in your hosted website too. I think you should check it out.

<img width="1248" alt="Screenshot 2024-09-09 at 3 16 26 AM" src="https://github.com/user-attachments/assets/7297f311-947f-4c42-b0c8-667ac276a221">

2024-09-09 17:00 UTC, Dun-sin commented
Thanks, will look into it

2024-09-12 09:41 UTC, Dun-sin commented
@LuseBiswas

2024-09-12 10:12 UTC, LuseBiswas commented
@Dun-sin I am so sorry...but actually I was little busy with my academics....I will make it ASAP.

2024-09-18 19:57 UTC, closed without merging