ci(github-actions): add Prettier auto-correct for lint issues on PRs
Dun-sin/Whisper pull request #714
Opened 2024-10-21 17:43 UTC by joshua-jinu

# Fixes Issue

**My PR closes #711**

# 👨‍💻 Changes proposed(What did you do ?)
- Addition of formatting using Prettier and ESLint on Pull Requests using Github Actions.

# ✔️ Check List (Check all the applicable boxes)

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.

##  Note to reviewers

# 📷 Screenshots

2024-10-21 17:51 UTC, Dun-sin commented
@joshua-jinu your lint fails

2024-10-21 17:51 UTC, Dun-sin commented
did you use chatgpt? looks like you didn't study the project structure to do this

2024-10-21 18:10 UTC, Dun-sin requested changes

2024-10-21 18:10 UTC, Dun-sin commented on .github/workflows/prettier-eslint.yml
> +          npm run format -- --write
no need for the extra options:
https://github.com/Dun-sin/Whisper/blob/c2dc613d32e1cfb41e11098db3bfe3cc19c2e723/client/package.json#L9-L10

2024-10-21 18:10 UTC, Dun-sin commented on .github/workflows/prettier-eslint.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
don't think any of this is important, try taking it out

2024-10-22 04:14 UTC, joshua-jinu commented
Hey @Dun-sin , I've made the changes, could you please review them

2024-10-22 08:33 UTC, Dun-sin commented on .github/workflows/prettier-eslint.yml
> +          cd ../client && npm i
```suggestion
          cd ./server && npm i
          cd ../client && npm i
```

2024-10-22 08:34 UTC, Dun-sin commented on .github/workflows/prettier-eslint.yml
> +          cd ../client && npm i
```suggestion
          cd ../client && npm i --force
```

2024-10-22 08:37 UTC, Dun-sin commented on .github/workflows/prettier-eslint.yml
> +        run: |
```suggestion
      - name: Run ESLint and Prettier
        working-directory: ./client
        run: |
```

2024-10-22 08:44 UTC, Dun-sin commented on .github/workflows/prettier-eslint.yml
> +          npm run format
```suggestion
name: Prettier Lint and Format
on:
  pull_request:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  prettier-lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: |
          cd ./server && npm i
          cd ../client && npm i --force
      - name: Run ESLint and Prettier
        working-directory: ./client
        run: |
          npm run lint
          npm run format
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "has_changes=true" >> $GITHUB_OUTPUT
      - name: Commit changes
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "style: format code with prettier and fix lint issues"
          git push
```

2024-10-22 08:48 UTC, Dun-sin commented on .github/workflows/prettier-eslint.yml
> +        uses: actions/checkout@v3
```suggestion
        uses: actions/checkout@v2
```

2024-10-22 08:54 UTC, Dun-sin commented on .github/workflows/prettier-eslint.yml
> +          git push
```suggestion
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: |
          cd ./server && npm i
          cd ../client && npm i --force
      - name: Run ESLint and Prettier
        working-directory: ./client
        run: |
          npm run lint
          npm run format
      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "has_changes=true" >> $GITHUB_OUTPUT
      - name: Commit changes
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "style: format code with prettier and fix lint issues"
          git add -A
          git push
```

2024-10-22 09:02 UTC, Dun-sin commented on .github/workflows/prettier-eslint.yml
> +  pull-requests: write
```suggestion
  push:
    branches:
      - main
      
permissions:
  contents: write
```

2024-10-22 09:04 UTC, Dun-sin approved these changes
You did great, thanks for contributing, I hope you will stick around and continue to contribute to this project.

Consider giving this project a star, sharing the project with your friends, and joining the community discord server if you haven't for more resources and opportunities to connect with others. [👉🏽here👈🏽](https://discord.com/invite/ufcysW9q23)

2024-10-22 09:04 UTC, merged

2024-10-22 09:05 UTC, joshua-jinu commented
Thank you @Dun-sin, looking forward to work on more such PRs